### ISSUE TITLE
an update of docker

### ISSUE THREAD

**Issue by viking76** [tradytics/surpriver#11]
Hi I have forked your repo and add feature to be build with docker great.
If you are interrest, I can Pull?

**Comment by tradytics** [comment]
There is already a docker build in the repo, no?

**Comment by tradytics** [comment]
Please do, I'll merge it.

**Comment by viking76** [comment]
rip in my fork the work is incomplete, sorry I need to do more test to complete this

**Comment by viking76** [comment]
I have made a container build in dockerhub . If you want to test It . Its here viking74000/surpriver but don't forget to set
On Environnement Variable :    CONFIG "C:\path\to\this\dir:/usr/src/app/" .
I have tested with synology server but i think its work on windows

**Comment by tradytics** [comment]
Closing this since another docker build has been submitted.
