### ISSUE TITLE
No file or directory: dictionaries/data_dict.npy

### ISSUE THREAD

**Issue by DoubleA11** [tradytics/surpriver#5]
Those who encounter this error, change the first command from this: 
`python detection_engine.py --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path 'dictionaries/data_dict.npy' --is_save_dictionary 1 --is_test 0 --future_bars 0`

And change this to:
`python detection_engine.py --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path dictionaries/data_dict.npy --is_save_dictionary 1 --is_test 0 --future_bars 0`

**Comment by tradytics** [comment]
Excellent information. I will close this issue now. Thanks a lot.
